### ISSUE TITLE
Hash Mismatch Crowsec Module

### ISSUE THREAD

**Issue by rhousand** [kampka/nix-flake-crowdsec#6]
It looks like the crowdsec hash is mismatched:

      error: 1 dependencies of derivation '/nix/store/gix25jk899dcays39f8gnlqxsl4j8kn2-crowdsec-1.6.0.drv' failed to build
┏━ 1 Errors:
┃ error: hash mismatch in fixed-output derivation '/nix/store/ggpc2ak464sninqjqaf1xhc3i7jakv33-2868.patc…
┃          specified: sha256-RSfLhNZ3JVvHoW/BNca9Hs4lpjcDtE1vsBDjJeaHqvc=
┃             got:    sha256-KLoGgHGwkS3+e0vSrivL0HQVRCCZ+saH9NDWlH7/Zmw=

**Comment by rhousand** [comment]
I found this is due to the fact I am using nixpkgs-unstable. I will do a PR on nixpkgs to push croudsec to v1.6.1. Then, I'll update my fork to work with nixpkgs-unstable. I will close this Issue and the PR connected.

**Comment by kampka** [comment]
Hi there, sorry for the late response.
There already is a PR to update [crowdsec on nixpkgs](https://github.com/NixOS/nixpkgs/pull/304526).
It's not uncommon though for nixpkgs PRs to take a while until someone with commit access will merge it.
I will probably internalize the crowdsec package into this flake and add it to the overlay on the weekend to have a better shot at timely maintenance.
